kind: pipeline
type: kubernetes
name: default-demo

steps:
  - name: helm-lint
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./charts

  - name: deploy-prod
    image: pelotech/drone-helm3
    settings:
      mode: upgrade
      chart: ./charts
      release: wpdemo 
      chart_version: ${DRONE_COMMIT_SHA:0:8}-prod
      namespace: wpdemo
    environment:
      KUBE_API_SERVER:
        from_secret: kubernetes_server
      KUBE_CERTIFICATE:
        from_secret: kubernetes_certificate
      KUBE_TOKEN:
        from_secret: kubernetes_token
      KUBE_SERVICE_ACCOUNT: default
