kind: pipeline
type: kubernetes
name: default

steps:
  - name: helm-lint
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./charts

  - name: deploy-prod
    image: pelotech/drone-helm3
    settings:
      mode: upgrade
      chart: ./charts
      release: wpdemo 
      chart_version: ${DRONE_COMMIT_SHA:0:8}-prod
      namespace: wpdemo

